-- ExploreX core tables (profiles, saved places, trips)

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.preferences (
  user_id uuid primary key references auth.users (id) on delete cascade,
  budget text,
  interests text[] not null default '{}',
  region text,
  updated_at timestamptz not null default now()
);

create table if not exists public.saved_places (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title text not null,
  wiki_url text,
  lat double precision,
  lon double precision,
  region text,
  created_at timestamptz not null default now()
);

create table if not exists public.trips (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title text not null,
  destination text not null,
  days int not null check (days >= 1 and days <= 30),
  budget text,
  interests text[] not null default '{}',
  itinerary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.preferences enable row level security;
alter table public.saved_places enable row level security;
alter table public.trips enable row level security;

create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);
create policy "profiles_upsert_own" on public.profiles for insert with check (auth.uid() = id);
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = id);

create policy "preferences_select_own" on public.preferences for select using (auth.uid() = user_id);
create policy "preferences_upsert_own" on public.preferences for insert with check (auth.uid() = user_id);
create policy "preferences_update_own" on public.preferences for update using (auth.uid() = user_id);

create policy "saved_places_select_own" on public.saved_places for select using (auth.uid() = user_id);
create policy "saved_places_insert_own" on public.saved_places for insert with check (auth.uid() = user_id);
create policy "saved_places_delete_own" on public.saved_places for delete using (auth.uid() = user_id);

create policy "trips_select_own" on public.trips for select using (auth.uid() = user_id);
create policy "trips_insert_own" on public.trips for insert with check (auth.uid() = user_id);
create policy "trips_update_own" on public.trips for update using (auth.uid() = user_id);
create policy "trips_delete_own" on public.trips for delete using (auth.uid() = user_id);

