-- User-generated reviews / testimonials (optional)

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  place_title text not null,
  quote text not null,
  rating int not null check (rating >= 1 and rating <= 5),
  trip_type text,
  region text,
  user_name text,
  user_image text,
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

-- Anyone can read reviews (public testimonials)
create policy "reviews_select_public" on public.reviews for select using (true);

-- Only signed-in users can insert their own review
create policy "reviews_insert_own" on public.reviews for insert with check (auth.uid() = user_id);

-- Only owner can update/delete
create policy "reviews_update_own" on public.reviews for update using (auth.uid() = user_id);
create policy "reviews_delete_own" on public.reviews for delete using (auth.uid() = user_id);

